### ISSUE TITLE
Some buttons look awful on OS X

### ISSUE THREAD

**Issue by hjri** [drevoborod/tasker#13]
<img width="726" alt="screen shot 2016-04-04 at 12 52 53" src="https://cloud.githubusercontent.com/assets/3514245/14244537/ab7e740e-fa6c-11e5-8fce-08d191b5199b.png">

**Comment by drevoborod** [comment]
Thanx for reporting! 
Actually the application had never been tested on Mac OS X. Will be fixed in future versions.

**Comment by drevoborod** [comment]
Fixed. Now buttons look identically awful on all platforms :)
![screen shot 2016-06-03 at 17 36 37](https://cloud.githubusercontent.com/assets/10282847/15782446/081828d4-29b3-11e6-8821-687976fa05e1.png)
